source: contents
update:
    documents:
        kex: all
    ai-mcp-rules:
        targets:
            - antigravity
        scopes:
            - coding
            - documentation
    ai-skills:
        targets: []
        keywords: []

baseURL: https://mew-ton.github.io/coding-guidelines/